name: "Backend: DEV PHP container"

# The versions of PHP and NGINX on this file are referenced by env vars set in the repository

on:
  # Run jobs manually in GitHub's UI
  workflow_dispatch:

jobs:
  build_php_80_node_20:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: ./.github/workflows/build-push.yml
        with:
          push: true
          tags: |
            tuskwhale/frankenphp-workspace:1.1-php8.0-node20-bookworm
            tuskwhale/frankenphp-workspace:1.1-php8.0
          build-args: |
            PHP_VERSION=8.0
            NODE_VERSION=20
            FRANKENPHP_VERSION=1.1