name: "FrankenPHP workspace build and push"
on:
  # Run jobs manually in GitHub's UI
  workflow_dispatch:

jobs:
  build_php_80_node_20:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/setup.yml

    steps:
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            tuskwhale/frankenphp-workspace:1.1-php8.0-node20-bookworm
            tuskwhale/frankenphp-workspace:1.1-php8.0
          build-args: |
            PHP_VERSION=8.0
            NODE_VERSION=20
            FRANKENPHP_VERSION=1.1