name: "Backend: DEV PHP container"

# The versions of PHP and NGINX on this file are referenced by env vars set in the repository

on:
  # Run jobs manually in GitHub's UI
  workflow_dispatch:

jobs:
  build_php_80_node_20:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    env:
      PHP_VERSION: 8.0
      NODE_VERSION: 20
      FRANKENPHP_VERSION: 1.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and push
        uses: ./.github/actions/build-push.yml