name: "FrankenPHP Build and Push"

on:
  # Run jobs manually in GitHub's UI
  workflow_dispatch:

jobs:
  build_php_80_node_20:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}
    env:
      PHP_VERSION: 8.0
      NODE_VERSION: 20
      FRANKENPHP_VERSION: 1.1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push
        uses: .github/actions/build-push
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}